
import __ASTRO_IMAGE_IMPORT_MF39r from "./thumbnail.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fimprove-concentration%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_nQVom from "./nikola-arsov-still-life-interior-design-vray-3ds-max-05-930px.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F3d-rendering%2Findex.md";
import __ASTRO_IMAGE_IMPORT_FKHe5 from "./thanos-dd-single-image-004a.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F3d-rendering%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1V3jJ7 from "./thumbnail.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F3d-rendering%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1qhkQx from "./thumbnail.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcustomize%2Findex.md";
import __ASTRO_IMAGE_IMPORT_2lFies from "./thumbnail.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmusic-journey%2Findex.md";
import __ASTRO_IMAGE_IMPORT_2g8SiL from "./thumbnail.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmarkdown%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Uy7Xs from "./thumbnail.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmarkdown-zh%2Findex.md";
export default new Map([["./thumbnail.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fimprove-concentration%2Findex.mdx", __ASTRO_IMAGE_IMPORT_MF39r], ["./nikola-arsov-still-life-interior-design-vray-3ds-max-05-930px.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F3d-rendering%2Findex.md", __ASTRO_IMAGE_IMPORT_nQVom], ["./thanos-dd-single-image-004a.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F3d-rendering%2Findex.md", __ASTRO_IMAGE_IMPORT_FKHe5], ["./thumbnail.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F3d-rendering%2Findex.md", __ASTRO_IMAGE_IMPORT_1V3jJ7], ["./thumbnail.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcustomize%2Findex.md", __ASTRO_IMAGE_IMPORT_1qhkQx], ["./thumbnail.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmusic-journey%2Findex.md", __ASTRO_IMAGE_IMPORT_2lFies], ["./thumbnail.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmarkdown%2Findex.md", __ASTRO_IMAGE_IMPORT_2g8SiL], ["./thumbnail.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fmarkdown-zh%2Findex.md", __ASTRO_IMAGE_IMPORT_Uy7Xs]]);
		